### ISSUE TITLE
Installation issueL gitlab/github

### ISSUE THREAD

**Issue by ycliu1987** [ADicksonLab/CSNAnalysis#1]
Hi Dr. Dickson

I just realized that the 'clone' command use 'gitlab' instead of 'github' as followed.
`git clone https://gitlab.com/ADicksonLab/CSNAnalysis`

I was asked for a gitlab.com username and password, so I did not further work on the gitlab address. I am not sure if you have the same source file on gitlab, but just a kind remind on this.

I succeeded in cloning it by replace 'gitlab' by 'github'. 

Yuanchao

**Comment by alexrd** [comment]
Replaced!  Thanks Yuanchao.
